# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\maiTaiControlTemplate.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(518, 399)
        MainWindow.setMinimumSize(QtCore.QSize(500, 350))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setStyleSheet(_fromUtf8("background-color: rgb(226, 226, 226);"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setSpacing(9)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.maitaiControlGroup = QtGui.QGroupBox(self.centralwidget)
        self.maitaiControlGroup.setObjectName(_fromUtf8("maitaiControlGroup"))
        self.gridLayout_15 = QtGui.QGridLayout(self.maitaiControlGroup)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.MaiTaiGroup_3 = QtGui.QGroupBox(self.maitaiControlGroup)
        self.MaiTaiGroup_3.setTitle(_fromUtf8(""))
        self.MaiTaiGroup_3.setObjectName(_fromUtf8("MaiTaiGroup_3"))
        self.gridLayout_16 = QtGui.QGridLayout(self.MaiTaiGroup_3)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.label_33 = QtGui.QLabel(self.MaiTaiGroup_3)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_16.addWidget(self.label_33, 5, 2, 1, 1)
        self.label_34 = QtGui.QLabel(self.MaiTaiGroup_3)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_16.addWidget(self.label_34, 4, 0, 1, 1)
        self.P2OptimizationLabel = QtGui.QLabel(self.MaiTaiGroup_3)
        self.P2OptimizationLabel.setText(_fromUtf8(""))
        self.P2OptimizationLabel.setObjectName(_fromUtf8("P2OptimizationLabel"))
        self.gridLayout_16.addWidget(self.P2OptimizationLabel, 5, 3, 1, 1)
        self.pumpLaserSystemStatusLabel = QtGui.QLabel(self.MaiTaiGroup_3)
        self.pumpLaserSystemStatusLabel.setText(_fromUtf8(""))
        self.pumpLaserSystemStatusLabel.setObjectName(_fromUtf8("pumpLaserSystemStatusLabel"))
        self.gridLayout_16.addWidget(self.pumpLaserSystemStatusLabel, 6, 1, 1, 1)
        self.label_37 = QtGui.QLabel(self.MaiTaiGroup_3)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_16.addWidget(self.label_37, 6, 0, 1, 1)
        self.label_36 = QtGui.QLabel(self.MaiTaiGroup_3)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_16.addWidget(self.label_36, 6, 2, 1, 1)
        self.systemStatusLabel = QtGui.QLabel(self.MaiTaiGroup_3)
        self.systemStatusLabel.setText(_fromUtf8(""))
        self.systemStatusLabel.setObjectName(_fromUtf8("systemStatusLabel"))
        self.gridLayout_16.addWidget(self.systemStatusLabel, 6, 3, 1, 1)
        self.relHumidityLabel = QtGui.QLabel(self.MaiTaiGroup_3)
        self.relHumidityLabel.setText(_fromUtf8(""))
        self.relHumidityLabel.setObjectName(_fromUtf8("relHumidityLabel"))
        self.gridLayout_16.addWidget(self.relHumidityLabel, 4, 3, 1, 1)
        self.label_35 = QtGui.QLabel(self.MaiTaiGroup_3)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_16.addWidget(self.label_35, 4, 2, 1, 1)
        self.pumpModeLabel = QtGui.QLabel(self.MaiTaiGroup_3)
        self.pumpModeLabel.setText(_fromUtf8(""))
        self.pumpModeLabel.setObjectName(_fromUtf8("pumpModeLabel"))
        self.gridLayout_16.addWidget(self.pumpModeLabel, 4, 1, 1, 1)
        self.label_32 = QtGui.QLabel(self.MaiTaiGroup_3)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_16.addWidget(self.label_32, 5, 0, 1, 1)
        self.pumpPowerLabel = QtGui.QLabel(self.MaiTaiGroup_3)
        self.pumpPowerLabel.setText(_fromUtf8(""))
        self.pumpPowerLabel.setObjectName(_fromUtf8("pumpPowerLabel"))
        self.gridLayout_16.addWidget(self.pumpPowerLabel, 5, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.EmissionLabel = QtGui.QLabel(self.MaiTaiGroup_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.EmissionLabel.setFont(font)
        self.EmissionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.EmissionLabel.setObjectName(_fromUtf8("EmissionLabel"))
        self.horizontalLayout.addWidget(self.EmissionLabel)
        self.InternalShutterLabel = QtGui.QLabel(self.MaiTaiGroup_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.InternalShutterLabel.setFont(font)
        self.InternalShutterLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.InternalShutterLabel.setObjectName(_fromUtf8("InternalShutterLabel"))
        self.horizontalLayout.addWidget(self.InternalShutterLabel)
        self.PulsingLabel = QtGui.QLabel(self.MaiTaiGroup_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PulsingLabel.setFont(font)
        self.PulsingLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.PulsingLabel.setObjectName(_fromUtf8("PulsingLabel"))
        self.horizontalLayout.addWidget(self.PulsingLabel)
        self.gridLayout_16.addLayout(self.horizontalLayout, 1, 0, 2, 4)
        self.gridLayout_15.addWidget(self.MaiTaiGroup_3, 1, 0, 1, 3)
        self.maitaiWavelengthGroup_3 = QtGui.QGroupBox(self.maitaiControlGroup)
        self.maitaiWavelengthGroup_3.setTitle(_fromUtf8(""))
        self.maitaiWavelengthGroup_3.setObjectName(_fromUtf8("maitaiWavelengthGroup_3"))
        self.gridLayout_17 = QtGui.QGridLayout(self.maitaiWavelengthGroup_3)
        self.gridLayout_17.setMargin(6)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.label_38 = QtGui.QLabel(self.maitaiWavelengthGroup_3)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_17.addWidget(self.label_38, 0, 0, 1, 1)
        self.wavelengthSpin_2 = SpinBox(self.maitaiWavelengthGroup_3)
        self.wavelengthSpin_2.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.wavelengthSpin_2.setSuffix(_fromUtf8(""))
        self.wavelengthSpin_2.setObjectName(_fromUtf8("wavelengthSpin_2"))
        self.gridLayout_17.addWidget(self.wavelengthSpin_2, 0, 2, 1, 1)
        self.currentWaveLengthLabel = QtGui.QLabel(self.maitaiWavelengthGroup_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.currentWaveLengthLabel.setFont(font)
        self.currentWaveLengthLabel.setText(_fromUtf8(""))
        self.currentWaveLengthLabel.setObjectName(_fromUtf8("currentWaveLengthLabel"))
        self.gridLayout_17.addWidget(self.currentWaveLengthLabel, 1, 2, 1, 1)
        self.label_39 = QtGui.QLabel(self.maitaiWavelengthGroup_3)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_17.addWidget(self.label_39, 1, 0, 1, 1)
        self.gridLayout_15.addWidget(self.maitaiWavelengthGroup_3, 2, 0, 1, 3)
        self.alignmentModeBtn = QtGui.QPushButton(self.maitaiControlGroup)
        self.alignmentModeBtn.setCheckable(True)
        self.alignmentModeBtn.setObjectName(_fromUtf8("alignmentModeBtn"))
        self.gridLayout_15.addWidget(self.alignmentModeBtn, 0, 2, 1, 1)
        self.turnOnOffBtn = QtGui.QPushButton(self.maitaiControlGroup)
        self.turnOnOffBtn.setStyleSheet(_fromUtf8(""))
        self.turnOnOffBtn.setCheckable(True)
        self.turnOnOffBtn.setFlat(False)
        self.turnOnOffBtn.setObjectName(_fromUtf8("turnOnOffBtn"))
        self.gridLayout_15.addWidget(self.turnOnOffBtn, 0, 0, 1, 1)
        self.InternalShutterBtn = QtGui.QPushButton(self.maitaiControlGroup)
        self.InternalShutterBtn.setCheckable(True)
        self.InternalShutterBtn.setObjectName(_fromUtf8("InternalShutterBtn"))
        self.gridLayout_15.addWidget(self.InternalShutterBtn, 0, 1, 1, 1)
        self.gridGroupBox = QtGui.QGroupBox(self.maitaiControlGroup)
        self.gridGroupBox.setObjectName(_fromUtf8("gridGroupBox"))
        self.gridLayout = QtGui.QGridLayout(self.gridGroupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.outputPowerLabel = QtGui.QLabel(self.gridGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.outputPowerLabel.setFont(font)
        self.outputPowerLabel.setText(_fromUtf8(""))
        self.outputPowerLabel.setObjectName(_fromUtf8("outputPowerLabel"))
        self.gridLayout.addWidget(self.outputPowerLabel, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridGroupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.samplePowerLabel = QtGui.QLabel(self.gridGroupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.samplePowerLabel.setFont(font)
        self.samplePowerLabel.setText(_fromUtf8(""))
        self.samplePowerLabel.setObjectName(_fromUtf8("samplePowerLabel"))
        self.gridLayout.addWidget(self.samplePowerLabel, 1, 1, 1, 1)
        self.gridLayout_15.addWidget(self.gridGroupBox, 3, 0, 1, 3)
        self.gridGroupBox1 = QtGui.QGroupBox(self.maitaiControlGroup)
        self.gridGroupBox1.setObjectName(_fromUtf8("gridGroupBox1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridGroupBox1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.gridGroupBox1)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.socketConnectionLabel = QtGui.QLabel(self.gridGroupBox1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.socketConnectionLabel.setFont(font)
        self.socketConnectionLabel.setObjectName(_fromUtf8("socketConnectionLabel"))
        self.gridLayout_2.addWidget(self.socketConnectionLabel, 1, 1, 1, 1)
        self.listenToSocketBtn = QtGui.QPushButton(self.gridGroupBox1)
        self.listenToSocketBtn.setCheckable(True)
        self.listenToSocketBtn.setAutoDefault(True)
        self.listenToSocketBtn.setDefault(True)
        self.listenToSocketBtn.setObjectName(_fromUtf8("listenToSocketBtn"))
        self.gridLayout_2.addWidget(self.listenToSocketBtn, 0, 0, 1, 2)
        self.gridLayout_15.addWidget(self.gridGroupBox1, 4, 0, 1, 3)
        self.gridLayout_3.addWidget(self.maitaiControlGroup, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setMinimumSize(QtCore.QSize(0, 60))
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.maitaiControlGroup.setTitle(_translate("MainWindow", "Mai Tai Control", None))
        self.label_33.setText(_translate("MainWindow", "P2 Optimization:", None))
        self.label_34.setText(_translate("MainWindow", "Pump Mode:", None))
        self.label_37.setText(_translate("MainWindow", "Pump Laser Status:", None))
        self.label_36.setText(_translate("MainWindow", "System Status:", None))
        self.label_35.setText(_translate("MainWindow", "relative Humidity:", None))
        self.label_32.setText(_translate("MainWindow", "Current Pump Power:", None))
        self.EmissionLabel.setText(_translate("MainWindow", "Emission Off", None))
        self.InternalShutterLabel.setText(_translate("MainWindow", "Laser Shutter Closed", None))
        self.PulsingLabel.setText(_translate("MainWindow", "Not Pulsing", None))
        self.label_38.setText(_translate("MainWindow", "Set Wavelength: ", None))
        self.label_39.setText(_translate("MainWindow", "Current Wavelength:", None))
        self.alignmentModeBtn.setText(_translate("MainWindow", "Alignment mode Off", None))
        self.turnOnOffBtn.setText(_translate("MainWindow", "Turn Laser On", None))
        self.InternalShutterBtn.setText(_translate("MainWindow", "Open Laser Shutter", None))
        self.label_4.setText(_translate("MainWindow", "Current Output Power:", None))
        self.label_8.setText(_translate("MainWindow", "Power at sample (calc.):", None))
        self.label.setText(_translate("MainWindow", "Socket connection:", None))
        self.socketConnectionLabel.setText(_translate("MainWindow", "inactive", None))
        self.listenToSocketBtn.setText(_translate("MainWindow", "Listen to Socket", None))

from pyqtgraph import SpinBox
